// src/components/FileManager.jsx
import React, { useState } from 'react';
import { motion } from 'framer-motion';
import Button from './ui/Button';
import Card from './ui/Card';

const FileManager = ({ showToast }) => {
  const [isRenaming, setIsRenaming] = useState(false);
  const [isOrganizing, setIsOrganizing] = useState(false);
  const [renameResults, setRenameResults] = useState(null);
  const [organizeResults, setOrganizeResults] = useState(null);

  const renameFolders = async () => {
    setIsRenaming(true);
    
    try {
      const result = await window.electron.renameFolders();
      
      if (result.success) {
        setRenameResults(result);
        showToast(`Successfully renamed ${result.renamed_count} folders`, 'success');
      } else {
        showToast(`Failed to rename folders: ${result.message}`, 'error');
      }
    } catch (error) {
      console.error('Folder renaming error:', error);
      showToast('An error occurred during folder renaming', 'error');
    } finally {
      setIsRenaming(false);
    }
  };

  const organizeFolders = async () => {
    setIsOrganizing(true);
    
    try {
      const result = await window.electron.organizeFolders();
      
      if (result.success) {
        setOrganizeResults(result);
        showToast(`Successfully organized ${result.moved_count} files`, 'success');
      } else {
        showToast(`Failed to organize files: ${result.message}`, 'error');
      }
    } catch (error) {
      console.error('File organization error:', error);
      showToast('An error occurred during file organization', 'error');
    } finally {
      setIsOrganizing(false);
    }
  };

  const resetResults = (type) => {
    if (type === 'rename') {
      setRenameResults(null);
    } else if (type === 'organize') {
      setOrganizeResults(null);
    }
  };

  return (
    <div className="file-manager">
      <div className="file-manager-header">
        <h2>File Manager</h2>
        <p>Batch rename folders and organize files automatically</p>
      </div>
      
      <div className="file-manager-content">
        <div className="cards-container">
          <Card title="Batch Rename Folders">
            <p>Clean up folder names by removing spaces, special characters, and converting to lowercase.</p>
            
            <div className="card-actions">
              <Button 
                onClick={renameFolders} 
                disabled={isRenaming}
                loading={isRenaming}
              >
                Select Parent Folder
              </Button>
              
              {renameResults && (
                <Button 
                  onClick={() => resetResults('rename')} 
                  variant="text"
                  size="small"
                >
                  Clear Results
                </Button>
              )}
            </div>
            
            {renameResults && (
              <motion.div 
                className="operation-results"
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                transition={{ duration: 0.3 }}
              >
                <h4>Results</h4>
                <p><strong>Total folders:</strong> {renameResults.total_count}</p>
                <p><strong>Renamed:</strong> {renameResults.renamed_count}</p>
                
                {renameResults.renamed_details && renameResults.renamed_details.length > 0 && (
                  <div className="renamed-list">
                    <h5>Renamed folders:</h5>
                    <ul>
                      {renameResults.renamed_details.slice(0, 5).map((item, index) => (
                        <li key={index}>
                          {item.old_name} → {item.new_name}
                        </li>
                      ))}
                      {renameResults.renamed_details.length > 5 && (
                        <li>...and {renameResults.renamed_details.length - 5} more</li>
                      )}
                    </ul>
                  </div>
                )}
              </motion.div>
            )}
          </Card>
          
          <Card title="Organize Files by Type">
            <p>Automatically organize files into folders based on file type (images, documents, videos, etc.).</p>
            
            <div className="card-actions">
              <Button 
                onClick={organizeFolders} 
                disabled={isOrganizing}
                loading={isOrganizing}
              >
                Select Folder
              </Button>
              
              {organizeResults && (
                <Button 
                  onClick={() => resetResults('organize')} 
                  variant="text"
                  size="small"
                >
                  Clear Results
                </Button>
              )}
            </div>
            
            {organizeResults && (
              <motion.div 
                className="operation-results"
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                transition={{ duration: 0.3 }}
              >
                <h4>Results</h4>
                <p><strong>Total files:</strong> {organizeResults.total_count}</p>
                <p><strong>Moved:</strong> {organizeResults.moved_count}</p>
                
                {organizeResults.categories && organizeResults.categories.length > 0 && (
                  <div className="categories-list">
                    <h5>File categories:</h5>
                    <ul>
                      {organizeResults.categories.map((category, index) => (
                        <li key={index}>
                          {category.name}: {category.count} files
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </motion.div>
            )}
          </Card>
        </div>
      </div>
    </div>
  );
};

export default FileManager;

// src/components/FileManager.vue
<template>
  <div class="file-manager">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <!-- 批量重命名文件夹 -->
      <div class="card bg-base-100 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">{{ $t('fileManager.renameTitle') }}</h2>
          <p>{{ $t('fileManager.renameDescription') }}</p>
          
          <div class="mt-4">
            <button class="btn btn-primary" @click="renameFolders" :disabled="isRenaming">
              <span v-if="isRenaming" class="loading loading-spinner"></span>
              {{ $t('fileManager.renameButton') }}
            </button>
            
            <div v-if="renameResults || isRenaming" class="result-area mt-4">
              <div class="flex justify-between items-center mb-2">
                <h3 class="font-bold">{{ $t('fileManager.resultTitle') }}</h3>
                <button v-if="renameResults" class="btn btn-xs btn-ghost" @click="resetRenameResults">
                  {{ $t('fileManager.clearResults') }}
                </button>
              </div>
              
              <div v-if="isRenaming" class="flex items-center justify-center p-4">
                <span class="loading loading-spinner loading-lg"></span>
              </div>
              
              <div v-else-if="renameResults" class="stats shadow w-full">
                <div class="stat">
                  <div class="stat-title">{{ $t('fileManager.totalFolders') }}</div>
                  <div class="stat-value">{{ renameResults.total_count }}</div>
                </div>
                
                <div class="stat">
                  <div class="stat-title">{{ $t('fileManager.renamedFolders') }}</div>
                  <div class="stat-value text-primary">{{ renameResults.renamed_count }}</div>
                </div>
              </div>
              
              <div v-if="renameResults && renameResults.renamed_details && renameResults.renamed_details.length > 0" 
                   class="mt-4">
                <div class="overflow-x-auto">
                  <table class="table table-zebra w-full">
                    <thead>
                      <tr>
                        <th>原名称</th>
                        <th>新名称</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr v-for="(item, index) in renameResults.renamed_details.slice(0, 5)" :key="index">
                        <td>{{ item.old_name }}</td>
                        <td>{{ item.new_name }}</td>
                      </tr>
                    </tbody>
                  </table>
                  
                  <div v-if="renameResults.renamed_details.length > 5" class="text-center mt-2 text-sm opacity-70">
                    显示前 5 项，共 {{ renameResults.renamed_details.length }} 项
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      <!-- 按类型整理文件 -->
      <div class="card bg-base-100 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">{{ $t('fileManager.organizeTitle') }}</h2>
          <p>{{ $t('fileManager.organizeDescription') }}</p>
          
          <div class="mt-4">
            <button class="btn btn-primary" @click="organizeFolders" :disabled="isOrganizing">
              <span v-if="isOrganizing" class="loading loading-spinner"></span>
              {{ $t('fileManager.organizeButton') }}
            </button>
            
            <div v-if="organizeResults || isOrganizing" class="result-area mt-4">
              <div class="flex justify-between items-center mb-2">
                <h3 class="font-bold">{{ $t('fileManager.resultTitle') }}</h3>
                <button v-if="organizeResults" class="btn btn-xs btn-ghost" @click="resetOrganizeResults">
                  {{ $t('fileManager.clearResults') }}
                </button>
              </div>
              
              <div v-if="isOrganizing" class="flex items-center justify-center p-4">
                <span class="loading loading-spinner loading-lg"></span>
              </div>
              
              <div v-else-if="organizeResults" class="stats shadow w-full">
                <div class="stat">
                  <div class="stat-title">{{ $t('fileManager.totalFiles') }}</div>
                  <div class="stat-value">{{ organizeResults.total_count }}</div>
                </div>
                
                <div class="stat">
                  <div class="stat-title">{{ $t('fileManager.movedFiles') }}</div>
                  <div class="stat-value text-primary">{{ organizeResults.moved_count }}</div>
                </div>
              </div>
              
              <div v-if="organizeResults && organizeResults.categories && organizeResults.categories.length > 0" 
                   class="mt-4">
                <h4 class="font-semibold mb-2">文件类别统计:</h4>
                <div class="grid grid-cols-2 gap-2">
                  <div v-for="(category, index) in organizeResults.categories" :key="index" 
                       class="badge badge-outline p-3">
                    {{ category.name }}: {{ category.count }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useToast } from '@/composables/useToast';

const isRenaming = ref(false);
const isOrganizing = ref(false);
const renameResults = ref(null);
const organizeResults = ref(null);
const { showToast } = useToast();

const renameFolders = async () => {
  try {
    isRenaming.value = true;
    const result = await window.electron.renameFolders();
    
    if (result.success) {
      renameResults.value = result;
      showToast(`成功重命名 ${result.renamed_count} 个文件夹`, 'success');
    } else {
      showToast(`文件夹重命名失败: ${result.message}`, 'error');
    }
  } catch (error) {
    console.error('Error renaming folders:', error);
    showToast('文件夹重命名出错', 'error');
  } finally {
    isRenaming.value = false;
  }
};

const organizeFolders = async () => {
  try {
    isOrganizing.value = true;
    const result = await window.electron.organizeFolders();
    
    if (result.success) {
      organizeResults.value = result;
      showToast(`成功整理 ${result.moved_count} 个文件`, 'success');
    } else {
      showToast(`文件整理失败: ${result.message}`, 'error');
    }
  } catch (error) {
    console.error('Error organizing folders:', error);
    showToast('文件整理出错', 'error');
  } finally {
    isOrganizing.value = false;
  }
};

const resetRenameResults = () => {
  renameResults.value = null;
};

const resetOrganizeResults = () => {
  organizeResults.value = null;
};
</script>
